### ISSUE TITLE
Materials leading up to the 2nd recitation

### ISSUE THREAD

**Issue by adisarid** [adisarid/intro_statistics_R#1]
@AfekIlayAdler In the 2nd recitation, I want you to cover "principles of tidyverse" a bit deeper. The 2nd recitation should be tilted more towards R and tidyverse than theory.

If you want to show the MLE example, that's ok but first cover data munging in tidyverse and then use the tidyverse commands in the example.

For example, `tibble` versus the classical classes (data.frame, list, matrix, vector). Also make sure you show examples for all the important commands you mentioned of `dplyr` (e.g., `select`, `mutate`, `filter`, etc.). 

Currently, you are just mentioning them in 02 - MLE.Rmd, but not showing enough of them. Make sure you show a lot of examples.

Maybe even walk through some example of actual analysis providing basic statistics such as average, std, etc.

**Comment by AfekIlayAdler** [comment]
ok, I'll fix it,
can you start uploading the first lectures so I will start working on EX 3
+4?

**Comment by adisarid** [comment]
resolved with Afek's latest commit c420094412f3b8e3b8a24d4fd64850c805c6bda9
